language: csharp
mono: none
sudo: required
dotnet: 6.0.201
branches:
  only:
    - master
script:
  - dotnet restore
  - dotnet build GalleryAPI.sln
  - dotnet test
notifications:
  email:
    on_success: never
    on_failure: always