name: build and test

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '5.0.405' # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test on unit test 
      run: dotnet test --no-build test/galleryapi.unittest/GalleryAPI.unittest.csproj /p:CollectCoverage=true  /p:CoverletOutput=../../converage/

    - name: Test on integration test
      run: dotnet test --no-build test/galleryapi.integrationtest/GalleryAPI.integrationtest.csproj /p:CollectCoverage=true /p:CoverletOutput=../../converage/ /p:MergeWith="../../converage/coverage.json" /p:CoverletOutputFormat="cobertura"
    
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.0.2
      # uses: joshjohanning/CodeCoverageSummary@v1.0.2
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md