name: build and test

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '6.0.201' # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test on unit test 
      run: dotnet test --no-build --configuration Release test/galleryapi.unittest/GalleryAPI.unittest.csproj /p:CollectCoverage=true /p:CoverletOutput=../../coverage/

    - name: Test on integration test
      run: dotnet test --no-build --configuration Release test/galleryapi.integrationtest/GalleryAPI.integrationtest.csproj /p:CollectCoverage=true /p:CoverletOutput=../../coverage/ /p:MergeWith="../../coverage/coverage.json" /p:CoverletOutputFormat="cobertura"
    
    - name: Copy Coverage To Predictable Location
      run: cp coverage/coverage.cobertura.xml coverage.cobertura.xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '10 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md